# Generated by Django 3.2.9 on 2021-12-07 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobifyapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='job_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobifyapi.jobtype'),
            preserve_default=False,
        ),
    ]
