# Generated by Django 3.2.9 on 2021-12-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobifyapi', '0002_joblisting_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='wage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
