# Generated by Django 3.2.9 on 2021-12-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobifyapi', '0003_joblisting_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobifyuser',
            name='isBusiness',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobifyuser',
            name='name',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
    ]
