# Generated by Django 3.2.9 on 2021-12-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobifyapi', '0004_auto_20211207_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='url',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
